build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    inputs: Baseten is a fast inference provider
    raw_scores: true
    truncate: true
    truncation_direction: Right
model_name: BEI-baseten-example-meta-llama-3-70b-instructforsequenceclassification-fp8-truss-example
python_version: py39
requirements: []
resources:
  accelerator: H100
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
trt_llm:
  build:
    base_model: encoder
    checkpoint_repository:
      repo: baseten/example-Meta-Llama-3-70B-InstructForSequenceClassification
      revision: main
      source: HF
    max_num_tokens: 16384
    num_builder_gpus: 2
    quantization_type: fp8
  runtime:
    webserver_default_route: /predict
