build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    max_tokens: 100
    messages:
    - content: Tell me everything about Baseten.co!
      role: user
    temperature: 0.3
model_name: Briton-mistralai-mistral-7b-instruct-v0.3-truss-example
python_version: py39
requirements: []
resources:
  accelerator: A10G
  cpu: '1'
  memory: 2Gi
  use_gpu: true
secrets: {}
system_packages: []
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      repo: mistralai/Mistral-7B-Instruct-v0.3
      revision: main
      source: HF
    max_seq_len: 32768
    quantization_type: no_quant
    tensor_parallel_count: 1
  runtime:
    enable_chunked_context: true
