build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    max_tokens: 2048
    messages:
    - content: Tell me everything you know about optimized inference.
      role: user
    stream: true
    temperature: 0.5
  tags:
  - openai-compatible
model_name: Qwen QwQ 32B
python_version: py39
requirements: []
resources:
  accelerator: H100
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      repo: Qwen/QwQ-32B
      revision: main
      source: HF
    max_seq_len: 131072
    num_builder_gpus: 4
    quantization_config:
      calib_max_seq_length: 4096
      calib_size: 3072
    quantization_type: fp8
    tensor_parallel_count: 1
  runtime:
    enable_chunked_context: true
