base_image:
  image: docker.io/baseten/trtllm-server:r23.12_baseten_v0.7.1
  python_executable_path: /usr/bin/python3
description: Mistral 7B Instruct, optimized with TRT-LLM for chat! Compatible with OpenAI Client
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/mistral_logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/mistral.png
  engine_repository: baseten/mistral_7b_instruct_fp16_tp1_32k
  example_model_input: {"messages": [{"role": "user", "content": "What is your favourite condiment?"}, {"role": "assistant", "content": "Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen!"}, {"role": "user", "content": "Do you have mayonnaise recipes?"}]}
  tags:
  - text-generation
  - openai-compatible
  tensor_parallelism: 1
  tokenizer_repository: mistralai/Mistral-7B-Instruct-v0.1
model_name: Mistral 7B Instruct Chat TRT-LLM 32k
python_version: py311
requirements:
- tritonclient[all]
- transformers
- jinja2
resources:
  accelerator: A100
  use_gpu: true
runtime:
  predict_concurrency: 256
model_cache:
  - repo_id: baseten/mistral_7b_instruct_fp16_tp1_32k
    allow_patterns:
      - "*.json"
      - "*.engine"
      - "*.cache"