model_name: sesame-csm-1b
python_version: py310
model_metadata:
  example_model_input:
    text: "Hello from Sesame."
    speaker: 0
requirements:
  - torch==2.4.0
  - torchaudio==2.4.0
  - tokenizers==0.21.0
  - transformers==4.49.0
  - huggingface_hub==0.28.1
  - moshi==0.2.2
  - torchtune==0.4.0
  - torchao==0.9.0
  - silentcipher @ git+https://github.com/SesameAILabs/silentcipher@master
  - ffmpeg
  - git+https://github.com/veerbia/csm.git
resources:
  accelerator: T4
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets:
  hf_access_token: null
system_packages: []
environment_variables: {}
external_package_dirs: []
