environment_variables:
  ENABLE_EXECUTOR_API: '1'
model_metadata:
  example_model_input:
    max_tokens: 512
    messages:
    - content: Tell me everything you know about optimized inference.
      role: user
    stream: true
    temperature: 0.5
  tags:
  - openai-compatible
model_name: Briton-qwen-qwq-32b-reasoning-with-speculative-fp8-truss-example
python_version: py39
resources:
  accelerator: H100
  cpu: '1'
  memory: 10Gi
  use_gpu: true
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      repo: Qwen/QwQ-32B
      revision: main
      source: HF
    max_batch_size: 64
    max_seq_len: 40960
    num_builder_gpus: 4
    quantization_config:
      calib_max_seq_length: 4096
      calib_size: 3072
    quantization_type: fp8
    speculator:
      lookahead_ngram_size: 5
      lookahead_verification_set_size: 5
      lookahead_windows_size: 7
      num_draft_tokens: 47
      speculative_decoding_mode: LOOKAHEAD_DECODING
    tensor_parallel_count: 1
  runtime:
    enable_chunked_context: true
