environment_variables: {}
external_package_dirs: []
description: Generate text from a prompt with this seven billion parameter language model.
model_metadata:
  tags:
  - text-generation
model_name: Mistral 7B Huggingface
python_version: py311
requirements:
- transformers==4.34.0
- sentencepiece
- accelerate
- torch==2.0.1
system_requirements: {}
resources:
  accelerator: H100
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 256