build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    max_tokens: 512
    messages:
    - content: Tell me everything you know about optimized inference.
      role: user
    stream: true
    temperature: 0.5
  tags:
  - openai-compatible
model_name: Briton-meta-llama-llama-3.3-70b-instruct-speculative-with-1b-external-draft-truss-example
python_version: py39
requirements: []
resources:
  accelerator: H100:2
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets:
  hf_access_token: null
system_packages: []
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      repo: meta-llama/Llama-3.3-70B-Instruct
      revision: main
      source: HF
    max_seq_len: 131072
    plugin_configuration:
      use_fp8_context_fmha: true
    quantization_type: fp8_kv
    speculator:
      checkpoint_repository:
        repo: meta-llama/Llama-3.2-1B-Instruct
        revision: main
        source: HF
      num_draft_tokens: 10
      speculative_decoding_mode: DRAFT_TOKENS_EXTERNAL
    tensor_parallel_count: 2
  runtime:
    enable_chunked_context: true
    kv_cache_free_gpu_mem_fraction: 0.45
