base_image:
  image: docker.io/baseten/trtllm-server:r23.12_baseten_v0.9.0.dev2024022000
  python_executable_path: /usr/bin/python3
description: Generate text from a prompt with this seven billion parameter language model.
model_name: Solar 10.7B
build:
  model_server: TRT_LLM
  arguments:
    engine_repository: "baseten/solar10.7"
    tokenizer_repository: "upstage/SOLAR-10.7B-Instruct-v1.0"
python_version: py311
environment:
  HF_HUB_ENABLE_HF_TRANSFER: true
requirements:
- tritonclient[all]
- hf_transfer
resources:
  accelerator: H100
  use_gpu: true
runtime:
  predict_concurrency: 256
