build_commands: []
environment_variables:
  ENABLE_EXECUTOR_API: 1
external_package_dirs: []
model_metadata:
  example_model_input:
    max_tokens: 512
    messages:
      - content: Tell me everything you know about optimized inference.
        role: user
    stream: true
    temperature: 0.5
  tags:
    - openai-compatible
model_name: Briton-meta-llama-llama-3.1-405b-fp8-truss-example
python_version: py39
requirements: []
resources:
  accelerator: H100:8
  cpu: "1"
  memory: 10Gi
  use_gpu: true
secrets:
  hf_access_token: null
system_packages: []
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      # presigned url from: https://us-east-2.console.aws.amazon.com/s3/buckets/mp-model-weights-public?bucketType=general&region=us-east-2&tab=objects#
      # feel free to reach out to us if you need access to this bucket
      repo: https://mp-model-weights-public.s3.us-east-2.amazonaws.com/llama-405b-tp8-fp8kv-tllm.tar
      source: REMOTE_URL
    max_seq_len: 131072
    plugin_configuration:
      use_fp8_context_fmha: true
    quantization_type: fp8_kv
    tensor_parallel_count: 8
  runtime:
    enable_chunked_context: true
