apply_library_patches: true
base_image: null
build:
  arguments:
    arguments:
      max_batch_size: 96
      max_input_len: 2000
      max_output_len: 2000
    pipeline_parallel_count: 1
    tensor_parallel_count: 1
    tokenizer_repository: Gryphe/MythoMax-L2-13b
  model_server: TRT_LLM
bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this seven billion parameter language
  model.
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_cache: []
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Mythomax 13b
model_type: Model
python_version: py311
requirements:
- tritonclient[all]
- hf_transfer
requirements_file: null
resources:
  accelerator: H100
  cpu: '1'
  memory: 2Gi
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 256
secrets: {}
spec_version: '2.0'
system_packages: []
train:
  resources:
    accelerator: null
    cpu: '1'
    memory: 2Gi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
